---
- name: Ensure the directory structure
  ansible.builtin.file:
    path: "/opt/pterodactyl/{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  loop:
    - "var"
    - "nginx"
    - "logs"

- name: Template the .env file for the Pterodactyl panel
  ansible.builtin.template:
    src: "templates/.env.j2"
    dest: "/opt/pterodactyl/.env"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

- name: Ensure the docker container is running
  community.docker.docker_container:
    name: panel
    image: "ghcr.io/pterodactyl/panel:{{ panel_pterodactyl_panel_version }}"
    state: started
    restart_policy: unless-stopped
    env_file: "/opt/pterodactyl/.env"
    volumes:
      - "/opt/pterodactyl/var/:/app/var/"
      - "/opt/pterodactyl/nginx/:/etc/nginx/http.d/"
      - "/opt/pterodactyl/logs/:/app/storage/logs"
    networks:
      - name: pterodactyl_databases
      - name: proxy_network
